### PR TITLE
Nicer text layout

### PR DESCRIPTION
**Pull request by phoglenix**

### CODE REVIEW

**Comment by phoglenix** [comment]
@SarenCurrie please merge if it's ok

**Comment by SarenCurrie** [comment]
Sorry Glen, There we’re a couple of things I wanted to tweak before merging and never got around to it, will do today or tomorrow.

> On 2015-06-29, at 11:39 , Glen <notifications@github.com> wrote:
> 
> Assigned #30 <https://github.com/ausesa/ausesa.github.com/pull/30> to @SarenCurrie <https://github.com/SarenCurrie>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ausesa/ausesa.github.com/pull/30#event-342445788>.
> 

---------------------------------------

The email public licence:

THIS EMAIL IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE EMAIL OR THE USE OR OTHER DEALINGS IN THE EMAIL.

**Comment by phoglenix** [comment]
That's ok I'll just keep poking you with notifications until you give in

**Comment by phoglenix** [comment]
:+1:

**Pull request merged**
